import { describe, expect, test } from "bun:test";
import {
  classifyRisk,
  createDefaultReviewConfig,
  filterDiff,
  isLowSignalPath,
  loadReviewFixture,
  matchesGlob,
  runReview,
} from "../src/index.ts";

describe("path glob matching", () => {
  test("matches root and nested ignored path patterns", () => {
    expect(matchesGlob("package-lock.json", "**/package-lock.json")).toBe(true);
    expect(matchesGlob("frontend/package-lock.json", "**/package-lock.json")).toBe(true);
    expect(matchesGlob("public/app.min.js", "**/*.min.js")).toBe(true);
    expect(matchesGlob("auth/accounts.ts", "auth/**")).toBe(true);
    expect(matchesGlob(".github/workflows/release.yml", ".github/workflows/**")).toBe(true);
  });
});

describe("diff filtering and risk classification", () => {
  test("filters low-value files but keeps generated sensitive migrations", async () => {
    const fixture = await loadReviewFixture("examples/fixtures/mixed-diff.json");
    const result = filterDiff(fixture.diff, fixture.config);

    expect(result.diff.files.map((file) => file.path)).toEqual([
      "src/app.ts",
      "migrations/20260609_add_accounts.sql",
      ".github/workflows/release.yml",
    ]);
    expect(result.ignoredFiles.map((ignored) => ignored.reason)).toEqual([
      "lockfile",
      "ignored_path",
      "binary",
    ]);
    expect(result.diff.totalAdditions).toBe(48);
    expect(result.diff.totalDeletions).toBe(4);
  });

  test("escalates filtered sensitive paths to full risk", async () => {
    const fixture = await loadReviewFixture("examples/fixtures/mixed-diff.json");
    const filtered = filterDiff(fixture.diff, fixture.config);
    const risk = classifyRisk({
      diff: filtered.diff,
      config: fixture.config,
      ignoredFileCount: filtered.ignoredFiles.length,
    });

    expect(risk.tier).toBe("full");
    expect(risk.matchedRules).toEqual(["sensitive_paths"]);
    expect(risk.sensitivePaths).toEqual([
      "migrations/20260609_add_accounts.sql",
      ".github/workflows/release.yml",
    ]);
    expect(risk.reviewedFileCount).toBe(3);
    expect(risk.ignoredFileCount).toBe(3);
  });

  test("ignores a file whose patch head carries a generated content marker (#24)", () => {
    const config = createDefaultReviewConfig();
    const result = filterDiff(
      {
        files: [
          { path: "src/app.ts", status: "modified", additions: 3, deletions: 0, isBinary: false },
          {
            path: "src/api-types.ts",
            status: "added",
            additions: 200,
            deletions: 0,
            isBinary: false,
            // marker is uppercased + has the diff `+` prefix; match is case-insensitive substring.
            patch: "@@ -0,0 +1,200 @@\n+// @GENERATED by openapi-codegen\n+export type Foo = {};\n",
          },
        ],
        totalAdditions: 203,
        totalDeletions: 0,
        truncated: false,
      },
      config,
    );

    expect(result.diff.files.map((file) => file.path)).toEqual(["src/app.ts"]);
    expect(result.ignoredFiles.map((ignored) => ignored.reason)).toEqual(["generated"]);
    // counted toward the ignored aggregate, not silently dropped.
    expect(result.ignoredFiles).toHaveLength(1);
  });

  test("never drops a sensitive file even when it carries a generated marker (#24)", () => {
    const config = createDefaultReviewConfig();
    const result = filterDiff(
      {
        files: [
          {
            // sensitive path (migrations/**) → short-circuit precedes marker detection.
            path: "migrations/20260613_gen.sql",
            status: "added",
            additions: 10,
            deletions: 0,
            isBinary: false,
            patch: "@@ -0,0 +1,10 @@\n+// @generated\n+CREATE TABLE t (id int);\n",
          },
        ],
        totalAdditions: 10,
        totalDeletions: 0,
        truncated: false,
      },
      config,
    );

    expect(result.diff.files.map((file) => file.path)).toEqual(["migrations/20260613_gen.sql"]);
    expect(result.ignoredFiles).toHaveLength(0);
  });

  test("config override replaces the marker set wholesale, re-including a default-dropped file (#24)", () => {
    // Override to a custom marker only → the default `// @generated` no longer drops anything.
    const config = { ...createDefaultReviewConfig(), generatedFileMarkers: ["// @codegen"] };
    const result = filterDiff(
      {
        files: [
          {
            path: "src/legacy.ts",
            status: "modified",
            additions: 4,
            deletions: 1,
            isBinary: false,
            patch: "@@ -1,4 +1,4 @@\n+// @generated\n+const x = 1;\n",
          },
        ],
        totalAdditions: 4,
        totalDeletions: 1,
        truncated: false,
      },
      config,
    );

    // `// @generated` is no longer a configured marker → file is reviewed.
    expect(result.diff.files.map((file) => file.path)).toEqual(["src/legacy.ts"]);
    expect(result.ignoredFiles).toHaveLength(0);
  });

  test("does not drop a file whose marker appears only on a deleted/context line (#24)", () => {
    const config = createDefaultReviewConfig();
    const result = filterDiff(
      {
        files: [
          {
            // The PR REMOVES the generated marker (it is on a `-` line) — scanning the raw patch
            // would falsely drop the file; only added (`+`) lines count, so it is reviewed.
            path: "src/was-generated.ts",
            status: "modified",
            additions: 1,
            deletions: 1,
            isBinary: false,
            patch: "@@ -1,2 +1,1 @@\n-// @generated\n const x = 1;\n",
          },
        ],
        totalAdditions: 1,
        totalDeletions: 1,
        truncated: false,
      },
      config,
    );

    expect(result.diff.files.map((file) => file.path)).toEqual(["src/was-generated.ts"]);
    expect(result.ignoredFiles).toHaveLength(0);
  });

  test("does not drop a file with no inline patch text even if markers are configured (#24)", () => {
    const config = createDefaultReviewConfig();
    const result = filterDiff(
      {
        files: [
          // patch offloaded to patchPath (large diff) → nothing cheap to scan → reviewed.
          {
            path: "src/big-generated.ts",
            status: "added",
            additions: 5000,
            deletions: 0,
            isBinary: false,
            patchPath: ".ai-review/patches/big-generated.ts.patch",
          },
        ],
        totalAdditions: 5000,
        totalDeletions: 0,
        truncated: false,
      },
      config,
    );

    expect(result.diff.files.map((file) => file.path)).toEqual(["src/big-generated.ts"]);
    expect(result.ignoredFiles).toHaveLength(0);
  });

  test("classifies ordinary 3-file small changes as trivial", () => {
    const config = createDefaultReviewConfig();
    const risk = classifyRisk({
      diff: {
        files: [
          { path: "src/a.ts", status: "modified", additions: 5, deletions: 0, isBinary: false },
          { path: "src/b.ts", status: "modified", additions: 5, deletions: 0, isBinary: false },
          { path: "docs/c.md", status: "modified", additions: 5, deletions: 0, isBinary: false },
        ],
        totalAdditions: 15,
        totalDeletions: 0,
        truncated: false,
      },
      config,
      ignoredFileCount: 0,
    });

    expect(risk.tier).toBe("trivial");
    expect(risk.matchedRules).toEqual(["small_change"]);
  });

  test("keeps 50-file ordinary changes lite and escalates 51-file changes to full", () => {
    const config = createDefaultReviewConfig();
    const files = Array.from({ length: 50 }, (_, index) => ({
      path: `src/file-${index}.ts`,
      status: "modified" as const,
      additions: 1,
      deletions: 0,
      isBinary: false,
    }));

    expect(
      classifyRisk({
        diff: {
          files,
          totalAdditions: 50,
          totalDeletions: 0,
          truncated: false,
        },
        config,
        ignoredFileCount: 0,
      }).tier,
    ).toBe("lite");

    expect(
      classifyRisk({
        diff: {
          files: [
            ...files,
            {
              path: "src/file-50.ts",
              status: "modified",
              additions: 1,
              deletions: 0,
              isBinary: false,
            },
          ],
          totalAdditions: 51,
          totalDeletions: 0,
          truncated: false,
        },
        config,
        ignoredFileCount: 0,
      }).tier,
    ).toBe("full");
  });

  test("still escalates sensitive paths even when the change is otherwise trivial", () => {
    const config = createDefaultReviewConfig();
    const risk = classifyRisk({
      diff: {
        files: [
          {
            path: ".github/workflows/release.yml",
            status: "modified",
            additions: 1,
            deletions: 0,
            isBinary: false,
          },
        ],
        totalAdditions: 1,
        totalDeletions: 0,
        truncated: false,
      },
      config,
      ignoredFileCount: 0,
    });

    expect(risk.tier).toBe("full");
    expect(risk.matchedRules).toEqual(["sensitive_paths"]);
  });

  test("runner context uses filtered diff", async () => {
    const fixture = await loadReviewFixture("examples/fixtures/mixed-diff.json");
    const result = await runReview({ fixture, now: new Date("2026-06-09T00:00:00.000Z") });

    expect(result.context.diff.files.map((file) => file.path)).toEqual([
      "src/app.ts",
      "migrations/20260609_add_accounts.sql",
      ".github/workflows/release.yml",
    ]);
    expect(result.summary.risk.ignoredFileCount).toBe(3);
    expect(result.summary.body).toContain("Files ignored: 3");
  });

  test("generated non-sensitive files are ignored", () => {
    const config = createDefaultReviewConfig();
    const result = filterDiff(
      {
        files: [
          {
            path: "src/generated/client.ts",
            status: "modified",
            additions: 100,
            deletions: 100,
            isBinary: false,
            isGenerated: true,
          },
        ],
        totalAdditions: 100,
        totalDeletions: 100,
        truncated: false,
      },
      config,
    );

    expect(result.diff.files).toHaveLength(0);
    expect(result.ignoredFiles[0]?.reason).toBe("generated");
  });
});

// ---------------------------------------------------------------------------
// isLowSignalPath — regression + classification table (#218, M021, #213 bar)
// ---------------------------------------------------------------------------

describe("isLowSignalPath — low-signal classifier (#218)", () => {
  // MUST be true: high-confidence bulk-data / snapshot paths

  test("__snapshots__/ path segment → low-signal", () => {
    expect(isLowSignalPath("test/__snapshots__/x.snap")).toBe(true);
  });

  test("*.snap extension → low-signal", () => {
    expect(isLowSignalPath("a.snap")).toBe(true);
    expect(isLowSignalPath("src/components/__snapshots__/button.snap")).toBe(true);
  });

  test("non-snap file under __snapshots__/ → low-signal (exercises the segment check directly)", () => {
    // A .json/.md under __snapshots__/ is NOT caught by extensionsAlways (.snap/.golden), so this
    // is the deciding case for the containsPathSegment(__snapshots__/) branch — without it the
    // branch could be deleted without any test failing.
    expect(isLowSignalPath("test/__snapshots__/data.json")).toBe(true);
    expect(isLowSignalPath("test/__snapshots__/notes.md")).toBe(true);
  });

  test("*.golden extension → low-signal", () => {
    expect(isLowSignalPath("x.golden")).toBe(true);
    expect(isLowSignalPath("test/golden/output.golden")).toBe(true);
  });

  test("examples/fixtures/ dir → low-signal (this repo's PR-fixture dir)", () => {
    expect(isLowSignalPath("examples/fixtures/auth-pr.json")).toBe(true);
    expect(isLowSignalPath("examples/fixtures/mixed-diff.json")).toBe(true);
  });

  test("pure-data file under test/fixtures/ → low-signal", () => {
    expect(isLowSignalPath("test/fixtures/data.json")).toBe(true);
    expect(isLowSignalPath("test/fixtures/seed.jsonl")).toBe(true);
    expect(isLowSignalPath("test/fixtures/readme.txt")).toBe(true);
    expect(isLowSignalPath("test/fixtures/export.csv")).toBe(true);
  });

  test("pure-data file under __fixtures__/ → low-signal", () => {
    expect(isLowSignalPath("src/__fixtures__/snapshot.json")).toBe(true);
  });

  // MUST be false: signal-bearing / logic files (the load-bearing regression cases)

  test("*.test.ts → NOT low-signal (even under fixtures dir)", () => {
    // M020 #213 regression case: test logic must NEVER be demoted
    expect(isLowSignalPath("src/runner/foo.test.ts")).toBe(false);
    expect(isLowSignalPath("test/foo.test.ts")).toBe(false);
    expect(isLowSignalPath("test/fixtures/builder.test.ts")).toBe(false);
  });

  test("*.spec.ts → NOT low-signal", () => {
    expect(isLowSignalPath("src/runner/foo.spec.ts")).toBe(false);
    expect(isLowSignalPath("test/fixtures/foo.spec.ts")).toBe(false);
  });

  test("*.test.tsx → NOT low-signal", () => {
    expect(isLowSignalPath("src/components/Button.test.tsx")).toBe(false);
  });

  test("source .ts under fixtures/ → NOT low-signal (could be fixture builder)", () => {
    expect(isLowSignalPath("test/fixtures/builder.ts")).toBe(false);
  });

  test("source file directly under an always-low-signal dir → NOT low-signal (pins sourceExtensions guard)", () => {
    // The sourceExtensions guard is the sole mechanism keeping a .ts/.js file out of low-signal
    // when it lives under __snapshots__/ or examples/fixtures/ (which otherwise match by segment).
    expect(isLowSignalPath("test/__snapshots__/helper.ts")).toBe(false);
    expect(isLowSignalPath("examples/fixtures/builder.ts")).toBe(false);
    expect(isLowSignalPath("examples/fixtures/build.js")).toBe(false);
  });

  test("normal source file → NOT low-signal", () => {
    expect(isLowSignalPath("src/runner/patch-admission.ts")).toBe(false);
    expect(isLowSignalPath("src/runner/diff-filter.ts")).toBe(false);
  });

  test("data file under a dir that merely CONTAINS 'fixtures' → NOT low-signal (segment-anchored)", () => {
    // Boundary-anchored matching: "fixtures/" must be a full path segment, so a dir like
    // `test-fixtures/` (which contains "fixtures/" as a substring) does NOT match — otherwise a
    // potentially security-relevant config data file would be wrongly demoted (AI-review #232).
    expect(isLowSignalPath("src/test-fixtures/config.json")).toBe(false);
    expect(isLowSignalPath("my-fixtures/data.json")).toBe(false);
  });

  test("examples/fixtures/*.md → low-signal (examples/fixtures/ has no extension guard)", () => {
    // examples/fixtures/ is this repo's PR-fixture dir and the pattern matches anything under it.
    // Spec says: "if you include .md, flip this case — just keep test and impl consistent."
    // Our impl has no extension guard on examples/fixtures/, so .md IS classified low-signal.
    expect(isLowSignalPath("examples/fixtures/notes.md")).toBe(true);
  });

  test("evals/fixtures/*.json → low-signal (fixtures/ + .json matches; demote≠drop, holdout #28)", () => {
    // evals/fixtures/ contains "fixtures/" segment + .json → classified low-signal by our rule.
    // This is acceptable per holdout hygiene (#28): don't TUNE patterns to pass evals.
    // Demotion ≠ dropping — eval fixtures remain in review as name+stat. Logic files in the
    // eval diffs (e.g. src/auth.ts) are NOT in fixtures/ and will NOT be demoted.
    expect(isLowSignalPath("evals/fixtures/auth-sqli.json")).toBe(true);
  });

  test("Windows-style paths (backslash) are normalized correctly", () => {
    expect(isLowSignalPath("test\\__snapshots__\\x.snap")).toBe(true);
    expect(isLowSignalPath("test\\fixtures\\data.json")).toBe(true);
    expect(isLowSignalPath("src\\runner\\foo.test.ts")).toBe(false);
  });
});
