import type { Finding, ReviewSummary } from "../contracts/index.ts";
import { escapeMarkdown } from "./markdown-escape.ts";

export interface SummaryMarkdownOptions {
  includeHiddenMetadata?: boolean;
  hiddenMetadata?: Record<string, unknown>;
}

export function formatReviewSummaryMarkdown(
  summary: ReviewSummary,
  options: SummaryMarkdownOptions = {},
): string {
  const lines: string[] = [
    `## ${summary.title}`,
    "",
    `**Decision:** \`${summary.decision}\``,
    `**CI outcome:** \`${summary.outcome}\``,
    `**Risk tier:** \`${summary.risk.tier}\``,
    "",
    summary.body,
    "",
    "### Findings",
    "",
  ];

  if (summary.findings.length === 0) {
    lines.push("No findings.");
  } else {
    for (const finding of summary.findings) {
      lines.push(formatFinding(finding));
      lines.push("");
    }
  }

  if (summary.reReview !== undefined) {
    lines.push("");
    lines.push("### Re-review status");
    lines.push("");
    lines.push(`- New findings: ${summary.reReview.newFindingIds.length}`);
    lines.push(`- Recurring findings: ${summary.reReview.recurringFindingIds.length}`);
    lines.push(`- Fixed prior findings: ${summary.reReview.fixedFindingIds.length}`);
    if (summary.reReview.fixedFindingIds.length > 0) {
      lines.push(
        `- Fixed IDs: ${summary.reReview.fixedFindingIds.map((id) => `\`${id}\``).join(", ")}`,
      );
    }
    lines.push(`- Withheld prior findings: ${summary.reReview.withheldFindingIds.length}`);
    if (summary.reReview.withheldFindingIds.length > 0) {
      lines.push(
        `- Withheld IDs: ${summary.reReview.withheldFindingIds.map((id) => `\`${id}\``).join(", ")}`,
      );
    }
  }

  lines.push("---");
  lines.push("_Generated by ai-code-review-factory._");

  if (options.includeHiddenMetadata === true) {
    lines.push("");
    lines.push("<!-- ai-code-review-factory");
    lines.push(JSON.stringify(options.hiddenMetadata ?? {}, null, 2));
    lines.push("-->");
  }

  return lines.join("\n").trimEnd();
}

function formatFinding(finding: Finding): string {
  const location = formatLocation(finding);
  // acknowledged.reason comes from the base-branch .ai-review.json — untrusted text (#74).
  const acknowledgedSuffix =
    finding.acknowledged !== undefined
      ? ` — _acknowledged: ${escapeMarkdown(finding.acknowledged.reason)}_`
      : "";
  const lines = [
    // title is LLM-produced — escape before embedding in bold text (#74).
    `- **${finding.severity.toUpperCase()}: ${escapeMarkdown(finding.title)}**${location}${acknowledgedSuffix}`,
    // category/reviewer/confidence are inside code spans (controlled-ish enums) — left as-is per spec.
    `  - Category: \`${finding.category}\``,
    `  - Reviewer: \`${finding.reviewer}\``,
    `  - Confidence: \`${finding.confidence}\``,
    // body and recommendation are LLM-produced free text — escape them (#74).
    `  - Why it matters: ${escapeMarkdown(finding.body)}`,
    `  - Recommendation: ${escapeMarkdown(finding.recommendation)}`,
  ];

  if (finding.evidence.length > 0) {
    // Escape each evidence entry individually before joining, so metacharacters in one
    // entry cannot bleed into the separator (#74).
    lines.push(`  - Evidence: ${finding.evidence.map((e) => escapeMarkdown(e)).join("; ")}`);
  }

  return lines.join("\n");
}

function formatLocation(finding: Finding): string {
  if (finding.location === undefined) {
    return "";
  }

  // path comes from the diff/VCS response — treat as untrusted text and escape it (#74).
  // Line numbers are numeric — no escaping needed.
  const { path, line, startLine, endLine } = finding.location;
  const escapedPath = escapeMarkdown(path);
  if (line !== undefined) {
    return ` (${escapedPath}:${line})`;
  }

  if (startLine !== undefined && endLine !== undefined) {
    return ` (${escapedPath}:${startLine}-${endLine})`;
  }

  return ` (${escapedPath})`;
}
