import type { Finding, ReviewSummary } from "../contracts/index.ts";

export interface SummaryMarkdownOptions {
  includeHiddenMetadata?: boolean;
  hiddenMetadata?: Record<string, unknown>;
}

export function formatReviewSummaryMarkdown(
  summary: ReviewSummary,
  options: SummaryMarkdownOptions = {},
): string {
  const lines: string[] = [
    `## ${summary.title}`,
    "",
    `**Decision:** \`${summary.decision}\``,
    `**CI outcome:** \`${summary.outcome}\``,
    `**Risk tier:** \`${summary.risk.tier}\``,
    "",
    summary.body,
    "",
    "### Findings",
    "",
  ];

  if (summary.findings.length === 0) {
    lines.push("No findings.");
  } else {
    for (const finding of summary.findings) {
      lines.push(formatFinding(finding));
      lines.push("");
    }
  }

  if (summary.reReview !== undefined) {
    lines.push("");
    lines.push("### Re-review status");
    lines.push("");
    lines.push(`- New findings: ${summary.reReview.newFindingIds.length}`);
    lines.push(`- Recurring findings: ${summary.reReview.recurringFindingIds.length}`);
    lines.push(`- Fixed prior findings: ${summary.reReview.fixedFindingIds.length}`);
    if (summary.reReview.fixedFindingIds.length > 0) {
      lines.push(`- Fixed IDs: ${summary.reReview.fixedFindingIds.map((id) => `\`${id}\``).join(", ")}`);
    }
  }

  lines.push("---");
  lines.push("_Generated by ai-code-review-factory._");

  if (options.includeHiddenMetadata === true) {
    lines.push("");
    lines.push("<!-- ai-code-review-factory");
    lines.push(JSON.stringify(options.hiddenMetadata ?? {}, null, 2));
    lines.push("-->");
  }

  return lines.join("\n").trimEnd();
}

function formatFinding(finding: Finding): string {
  const location = formatLocation(finding);
  const acknowledgedSuffix = finding.acknowledged !== undefined
    ? ` — _acknowledged: ${finding.acknowledged.reason}_`
    : "";
  const lines = [
    `- **${finding.severity.toUpperCase()}: ${finding.title}**${location}${acknowledgedSuffix}`,
    `  - Category: \`${finding.category}\``,
    `  - Reviewer: \`${finding.reviewer}\``,
    `  - Confidence: \`${finding.confidence}\``,
    `  - Why it matters: ${finding.body}`,
    `  - Recommendation: ${finding.recommendation}`,
  ];

  if (finding.evidence.length > 0) {
    lines.push(`  - Evidence: ${finding.evidence.join("; ")}`);
  }

  return lines.join("\n");
}

function formatLocation(finding: Finding): string {
  if (finding.location === undefined) {
    return "";
  }

  const { path, line, startLine, endLine } = finding.location;
  if (line !== undefined) {
    return ` (${path}:${line})`;
  }

  if (startLine !== undefined && endLine !== undefined) {
    return ` (${path}:${startLine}-${endLine})`;
  }

  return ` (${path})`;
}
